[package]
name = "lambda1"
version = "0.1.0"
authors = ["mimi <allthatjazz@outlook.com>"]
edition = "2018"


[dependencies]
lambda_runtime = "0.2.1"
serde = { version = "^1.0", features = ["derive"] }
